// Known-answer test for HMAC-SHA256, run at boot. Generated by the backend:
//   key = bytes 0x00..0x1f, message = command_canonical("esp32_01", 1700000000000, "PING")
// tests/test_firmware_consistency.py recomputes this with idps/protocol.py.
#pragma once

#define IDPS_KAT_MESSAGE "v1|cmd|esp32_01|1700000000000|PING"
#define IDPS_KAT_MAC_HEX "ef976d0a669bcf5bb8cd32d10ca0a0570cb7b3aaea6f1a89a02d129ddfa7efa1"
